-- ============================================
-- CSDL QUẢN LÝ THU CHI CÁ NHÂN (DÀNH CHO ADMIN)
-- ============================================

-- Bảng Role
CREATE TABLE Role (
    idrole INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rolename VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(255)
);

insert into Role (rolename, description)
values ('admin', 'quản trị viên hệ thống'),
       ('user','người dùng');

-- Bảng Account
CREATE TABLE Account (
    idaccount INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    idrole INTEGER NOT NULL,
    CONSTRAINT fk_account_role FOREIGN KEY (idrole) REFERENCES Role(idrole) ON DELETE RESTRICT
);

-- Bảng User (đặt tên trong ngoặc kép vì là từ khóa của PostgreSQL)
CREATE TABLE "User" (
    iduser INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(15),
    address VARCHAR(255),
    location CHAR(5),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    idaccount INTEGER NOT NULL UNIQUE,
    CONSTRAINT fk_user_account FOREIGN KEY (idaccount) REFERENCES Account(idaccount) ON DELETE CASCADE
);

-- Bảng Category
CREATE TABLE Category (
    idcategory INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    namecategory VARCHAR(100) NOT NULL,
    classify VARCHAR(10) NOT NULL CHECK (classify IN ('thu', 'chi', 'vay/no')),
    is_default BOOLEAN DEFAULT FALSE,
    created_by INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_category_account FOREIGN KEY (created_by) REFERENCES Account(idaccount) ON DELETE CASCADE
);

-- Bảng AuditLog
CREATE TABLE AuditLog (
    idlog INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idaccount INTEGER NOT NULL,
    action TEXT,
    details TEXT,
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_actionlog_account FOREIGN KEY (idaccount) REFERENCES Account(idaccount) ON DELETE CASCADE
);