-- ============================================
-- WealthCommand Backend
-- Script: Tạo bảng RefreshToken
-- Database: PersonFinance (PostgreSQL 18)
-- Ngày: 2026-08-01
-- ============================================

-- ============================================
-- 1. TẠO BẢNG RefreshToken
-- ============================================
CREATE TABLE RefreshToken (
    idtoken     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash  VARCHAR(255) NOT NULL UNIQUE,    -- SHA-256 hash của refresh token JWT
    idaccount   INTEGER NOT NULL,                 -- FK → Account
    idrole      INTEGER NOT NULL DEFAULT 2,       -- 1=admin, 2=user (tránh JOIN khi kiểm tra quyền)
    expiry      TIMESTAMP NOT NULL,               -- Thời gian hết hạn
    revoked     BOOLEAN DEFAULT FALSE,            -- TRUE = đã thu hồi
    device_name VARCHAR(100),                     -- Tên thiết bị (vd: "Chrome Windows", "iPhone 15")
    ip_address  VARCHAR(45),                      -- IPv4 hoặc IPv6
    user_agent  TEXT,                             -- User-Agent string
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- FK: xóa cascade khi tài khoản bị xóa
    CONSTRAINT fk_refreshtoken_account 
        FOREIGN KEY (idaccount) 
        REFERENCES Account(idaccount) 
        ON DELETE CASCADE
);

-- ============================================
-- 2. INDEXES (tối ưu truy vấn)
-- ============================================
CREATE INDEX idx_refreshtoken_token_hash ON RefreshToken(token_hash);
CREATE INDEX idx_refreshtoken_account    ON RefreshToken(idaccount);
CREATE INDEX idx_refreshtoken_expiry     ON RefreshToken(expiry);
CREATE INDEX idx_refreshtoken_revoked    ON RefreshToken(revoked);

-- ============================================
-- 3. TRIGGER: tự động cập nhật updated_at
-- ============================================
CREATE OR REPLACE FUNCTION update_refreshtoken_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_refreshtoken_updated_at
    BEFORE UPDATE ON RefreshToken
    FOR EACH ROW
    EXECUTE FUNCTION update_refreshtoken_updated_at();

-- ============================================
-- 4. CONSTRAINT: expiry > created_at
-- ============================================
ALTER TABLE RefreshToken 
    ADD CONSTRAINT chk_expiry_after_created 
    CHECK (expiry > created_at);

-- ============================================
-- 5. VERIFY
-- ============================================
-- Kiểm tra bảng đã tạo thành công
SELECT 
    'RefreshToken' AS table_name,
    COUNT(*) AS column_count
FROM information_schema.columns 
WHERE table_name = 'RefreshToken';

-- Xem cấu trúc bảng
-- \d+ RefreshToken

-- ============================================
-- GHI CHÚ SAU KHI CHẠY SCRIPT NÀY:
-- ============================================
-- Chạy lệnh sau trong thư mục Backend:
--   1. npx prisma db pull         (đồng bộ schema từ CSDL)
--   2. npx prisma generate        (tạo Prisma Client mới)
-- ============================================
